void printLine(int colWidth, int numCols);
void user_home();
void menu();
void cart();
void cart_result();
void receipt();
void rg();
void login();
void tea();
void coffee();
void soda();
void user_login();
void update_drink();